# Generated by Django 2.2.13 on 2021-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_end', '0004_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
