# Generated by Django 2.2.13 on 2021-07-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Front_end', '0006_speaker_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('attend_status', models.CharField(choices=[('waiting', 'Waiting'), ('attending', 'Attending'), ('completed', 'Completed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='Absent', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('active', 'Active'), ('deleted', 'Deleted'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='Active', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front_end.Event')),
            ],
            options={
                'unique_together': {('event', 'phone')},
            },
        ),
    ]
