# Generated by Django 2.2.13 on 2021-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_end', '0007_eventmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('sponsor_level', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=50)),
            ],
        ),
    ]
