# Generated by Django 2.2.13 on 2021-07-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_summarymodel_picture'),
        ('Front_end', '0009_galary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front_end.Speaker')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.summaryModel')),
            ],
        ),
    ]
