# Generated by Django 2.2.13 on 2021-06-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='summaryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('summary_title', models.CharField(max_length=20)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.summaryModel')),
            ],
        ),
    ]
