# Generated by Django 2.2.13 on 2021-06-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarymodel',
            old_name='summary',
            new_name='summary_detail',
        ),
    ]
